name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hi GitHub Actions!"
      - name: Say goodbye
        run: echo "See you later!"
